networks:
  grafana:
services:
  influxdb:
    image: influxdb:1.8
    networks:
      - grafana
    ports:
      - "8087:8086"
    environment:
      - INFLUXDB_DB=k6
  grafana:
    image: grafana/grafana:latest
    networks:
      - grafana
    ports:
      - "3001:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
    volumes:
      - ./dashboards:/var/lib/grafana/dashboards
      - ./grafana-dashboard.yaml:/etc/grafana/provisioning/dashboards/dashboard.yaml
      - ./grafana-datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml
